### ISSUE TITLE
can we secure communication with xxtea algorythim?

### ISSUE THREAD

**Issue by halukmy** [sandeepmistry/arduino-LoRa#161] opened 2018-06-17 14:12 UTC
https://github.com/boseji/xxtea-iot-crypt

i just find this crypt algorythim

so can we secure our lora message from sniffers with that algorythim?

thanks

**Comment by Yury-MonZon** [comment] 2018-06-22 18:10
Of course. You can use any encryption that you like, just mind the extra bytes added.

**Comment by sandeepmistry** [comment] 2018-07-30 23:09
Duplicate of https://github.com/sandeepmistry/arduino-LoRa/issues/155.

**Closed by sandeepmistry** 2018-07-30 23:09 UTC
Labels: duplicate
