### ISSUE TITLE
Xx-tea cryptology algorythm for lora-arduino

### ISSUE THREAD

**Issue by halukmy** [sandeepmistry/arduino-LoRa#162] opened 2018-06-19 13:09 UTC
@dontsovcmc 

i happy to see you starred that repo, so you think xx-tea-iot for lora-arduino secure?

**Comment by dontsovcmc** [comment] 2018-06-19 13:27
I know, that XTEA algorithm is easy way to secure your data for embedded devices. As you know secure for one project isn't secure for another. I don't read abstracts about serurity in IoT.

info: https://en.wikipedia.org/wiki/XTEA
online: https://sanstv.ru/tools/crypt/alg-xtea

**Comment by halukmy** [comment] 2018-06-19 13:38
thanks for share,

on our repo lets think about secure communication,

first i secure my message is "on1" to "@3W1£e" it loraX message


my key is "loraX"

sending one node works "as gateway" to another node this crypted message

on node side,  key is "loraX"

than uncrypt message and turn on light for example..

if someone sniff my lora message and send this message "@3W1£e" , node will act again as me..

so how i can secure it from any copier or sniffer my lora node ?

**Comment by dontsovcmc** [comment] 2018-06-19 14:05
I don't know ISO about cryptography, but I think you can read this article:
1. HTTP Digest auth solve your problem https://en.wikipedia.org/wiki/Digest_access_authentication
2. simple way: use random number and increase it every message
3. Google solving this: https://en.wikipedia.org/wiki/Replay_attack

**Comment by dontsovcmc** [comment] 2018-06-19 23:20
example message fields:
| device id (uint32) | random (uint32) | message id from 0 (uint32) | body |

When you receive message you should increase message id.
When you receive message with id != id +1 - ignore it.

**Comment by sandeepmistry** [comment] 2018-07-30 23:09
@halukmy please stop opening duplicate issues on this repo.

Duplicate of #155 and #161.

**Closed by sandeepmistry** 2018-07-30 23:09 UTC
